apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values
  # echo -n "your_value" | base64
  # Example: postgres -> cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: YXBwX2Ri
  SECRET_KEY: c3VwZXJzZWNyZXRrZXk= 
  ALGORITHM: SFMyNTY= 
